name: taxi_driver
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.2.7+8

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # BASE
  intl: ^0.19.0
  google_fonts: ^6.2.1
  html: ^0.15.4
  shared_preferences: ^2.2.2
  flutter_widget_from_html: ^0.14.11

  # TOAST
  fluttertoast: ^8.2.4

  # IMAGE
  cached_network_image: ^3.3.1

  # UI
  sliding_up_panel: ^2.0.0+1
  dotted_line: ^3.2.2
  lottie: ^3.1.0
  flutter_rating_bar: ^4.0.1
  flutter_staggered_animations: ^1.1.1
  bottom_picker: ^2.4.0
  country_code_picker: ^3.0.0
  flutter_native_contact_picker: ^0.0.6
  timeline_tile: ^2.0.0
  flutter_vector_icons: ^2.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_switch: ^0.3.2
  syncfusion_flutter_charts: ^27.1.53

  #OTP TEXT FIELD
  otp_text_field: ^1.1.3

  #MAP
  geolocator: ^13.0.1
  geocoding: ^2.2.1
  google_maps_flutter: ^2.7.0
  flutter_polyline_points: ^2.0.0
  location: ^7.0.0

  #IMAGES
  image_picker: ^1.0.7
  file_picker: ^6.2.0
  date_time_picker: ^2.1.0

  #CONNECTIVITY
  package_info_plus: ^5.0.1
  http: ^1.2.1
  connectivity_plus: ^5.0.2
  url_launcher: ^6.2.5
  map_launcher: ^3.2.0

  #FIREBASE
  firebase_crashlytics: ^3.4.18
  firebase_core: ^2.27.0
  firebase_auth: ^4.17.8
  firebase_storage: ^11.6.9
  firebase_database: ^10.4.9
  paginate_firestore: ^1.0.3+1
  cloud_firestore: ^4.15.8

  #STATE MANAGEMENT
  mobx: ^2.3.0+1
  flutter_mobx: ^2.2.0

  #PAYMENT GATEWAY
  # razorpay_flutter: ^1.3.6
  # flutter_stripe: ^10.1.1
  # flutter_paystack: ^1.0.7
  # flutter_braintree: ^4.0.0
  # flutterwave_standard: ^1.0.8
  # flutter_paytabs_bridge: ^2.6.7
  #  mercado_pago_mobile_checkout: ^0.2.0-dev.3
  # my_fatoorah: ^3.3.0
  # paytm: ^3.0.1

  # PUSH NOTIFICATION
  onesignal_flutter: ^5.1.2

  #SOCIAL LOGIN
  google_sign_in: ^6.2.1
  the_apple_sign_in: ^1.1.1

  #MQTT
  mqtt_client: ^10.2.0

  #DOWNLOAD INVOICE PDF
  pdf: ^3.10.8
  path_provider: ^2.1.2
  open_file: ^3.3.2
  printing: ^5.12.0
  flutter_ringtone_player: ^4.0.0+2
  pdf_widget_wrapper: ^1.0.4

  flutter_localizations:
    sdk: flutter
  intl_phone_field: ^3.2.0
  pinput: ^4.0.0
  flutter_easyloading: ^3.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.8
  mobx_codegen: ^2.6.0+1
  flutter_native_splash: ^2.4.1
  #flutter packages pub run build_runner build --delete-conflicting-outputs

dependency_overrides:
  intl: ^0.18.0
  http: ^0.13.5
  cloud_firestore: ^4.8.1
  package_info_plus: ^4.1.0
  web: 0.3.0
  archive: ^3.5.0
  win32: ^5.5.4

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "images/icon_jawad_driver.png"
  remove_alpha_ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/
    - images/
    - images/icons/
    - images/flag/
    - images/ringtone.mp3
  fonts:
    - family: Tajawal
      fonts:
        - asset: assets/fonts/TajawalRegular.ttf
          weight: 400
