// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgRNTOCg7SKXRXuW-ZKBM3sUkOhT1DkJI',
    appId: '1:633061968920:web:7f30f2035147798bdd476d',
    messagingSenderId: '633061968920',
    projectId: 'sawayer-b6add',
    authDomain: 'sawayer-b6add.firebaseapp.com',
    storageBucket: 'sawayer-b6add.appspot.com',
    measurementId: 'G-5XWZNW5G6V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgh9ys12UucB5g2by5bMQJnQJMmRx44sM',
    appId: '1:228402230352:android:e9f4baed45eef53846cd55',
    messagingSenderId: '228402230352',
    projectId: 'danbeauty-937c5',
    databaseURL: 'https://danbeauty-937c5-default-rtdb.firebaseio.com',
    storageBucket: 'danbeauty-937c5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAo_awcBKxIFn0nUxl-G0lk8eDL9-OWxYI',
    appId: '1:228402230352:ios:28016702a409817346cd55',
    messagingSenderId: '228402230352',
    projectId: 'danbeauty-937c5',
    databaseURL: 'https://danbeauty-937c5-default-rtdb.firebaseio.com',
    storageBucket: 'danbeauty-937c5.appspot.com',
    androidClientId: '228402230352-1tn0co2ikil8ldbua6mqoedbqehtesfq.apps.googleusercontent.com',
    iosClientId: '228402230352-gehdh1m4j6lilcbkf4s7hichjq8vtem0.apps.googleusercontent.com',
    iosBundleId: 'com.jawad.driver',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBTXQlMTjF6xKMREfl6WpfqgJuNkjQHB0g',
    appId: '1:633061968920:ios:cf80b9887005067fdd476d',
    messagingSenderId: '633061968920',
    projectId: 'sawayer-b6add',
    storageBucket: 'sawayer-b6add.appspot.com',
    iosBundleId: 'com.mighty.sawayerDriver',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBgRNTOCg7SKXRXuW-ZKBM3sUkOhT1DkJI',
    appId: '1:633061968920:web:f42f958869859993dd476d',
    messagingSenderId: '633061968920',
    projectId: 'sawayer-b6add',
    authDomain: 'sawayer-b6add.firebaseapp.com',
    storageBucket: 'sawayer-b6add.appspot.com',
    measurementId: 'G-ZK78D3LMXP',
  );
}